//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinxSolutionProiect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.Web.Mvc;

    public partial class Employee
    {


        public int UserId { get; set; }
        //Client Side validation
        [Required(ErrorMessage = "This field is required!")]
        public string UserName { get; set; }
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        [RegularExpression(@"^?[+. ]?([0-9]{2})?([0-9]{9})$", ErrorMessage = "Invalid Phone number")]
        public string PhoneNumber { get; set; }

        [Remote("IsEmpNameandMailExist", "Validation", ErrorMessage = "EmialId is already exist")]
        public string EmailAddress { get; set; }

        [DisplayName("Image")]
        public string ImagePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }


        public Nullable<System.DateTime> Birthday { get; set; }

        public Employee()
        {
            ImagePath = "~/AppFiles/Images/icon.jpg";
        }
  
    }
}
